apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: inference-gke-sa@int3319-477808.iam.gserviceaccount.com
  creationTimestamp: "2025-11-23T08:08:19Z"
  name: inference-pod-sa
  namespace: default
  resourceVersion: "1763885308817599024"
  uid: b0bed43d-4d11-4411-ba64-b9d58534d91d
