apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inference-hpa
spec:

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inference

  minReplicas: 2
  maxReplicas: 5

  metrics:
  - type: External
    external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: "inference_sub"
      target:
        type: AverageValue
        averageValue: 60

  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
